# Generated by Django 5.2.3 on 2025-06-30 15:22

import django.db.models.deletion
import pos_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenudetail',
            name='menu_resto',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='table_resto',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='waitress',
        ),
        migrations.RemoveField(
            model_name='ordermenudetail',
            name='order_menu',
        ),
        migrations.RemoveField(
            model_name='ordermenudetail',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='ordermenudetail',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='tableresto',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='tableresto',
            name='user_update',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_on',
            new_name='create_on',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Half Face', 'Half Face'), ('Full Face', 'Full Face')], max_length=15),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], max_length=15),
        ),
        migrations.CreateModel(
            name='JenisPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Tunai', 'Tunai'), ('Debit', 'Debit'), ('Kredit', 'Kredit'), ('Transfer', 'Transfer')], default='Tunai', max_length=15)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_jenis_pembayaran', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_jenis_pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=15)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_histori_pembayaran', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_histori_pembayaran', to=settings.AUTH_USER_MODEL)),
                ('jenis_pembayaran', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='histori_pembayaran', to='pos_app.jenispembayaran')),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=pos_app.models.increment_Layanan_code, editable=False, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(default='-')),
                ('image_menu', models.ImageField(blank=True, default='default_images/empt.jpg', null=True, upload_to='menu_images/')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_menu', to='pos_app.category')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_of_menu', to='pos_app.statusmodel')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_layanan', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_layanan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bayar', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=15)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('Jenis_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='pos_app.jenispembayaran')),
                ('Layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='pos_app.layanan')),
                ('code', models.ForeignKey(default=pos_app.models.increment_Layanan_code, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_code', to='pos_app.layanan')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_pembayaran', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuResto',
        ),
        migrations.DeleteModel(
            name='OrderMenu',
        ),
        migrations.DeleteModel(
            name='OrderMenuDetail',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TableResto',
        ),
    ]
