# Generated by Django 5.2.3 on 2025-06-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_remove_ordermenudetail_menu_resto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='code',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_code', to='pos_app.layanan'),
        ),
    ]
