# Generated by Django 5.2.3 on 2025-06-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_alter_layanan_code_alter_pembayaran_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='code',
        ),
    ]
