# Generated by Django 5.2.3 on 2025-06-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_remove_pembayaran_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanan',
            name='code',
        ),
    ]
