# Generated by Django 5.2.3 on 2025-06-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_remove_layanan_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriPembayaran',
        ),
    ]
