# Generated by Django 5.2.3 on 2025-07-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_delete_historipembayaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='Jenis_pembayaran',
            new_name='jenis_pembayaran',
        ),
        migrations.RenameField(
            model_name='pembayaran',
            old_name='Layanan',
            new_name='layanan',
        ),
    ]
