# Generated by Django 5.2.3 on 2025-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_rename_jenis_pembayaran_pembayaran_jenis_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenispembayaran',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jenispembayaran',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
